[build]
	# Where to serve site from
	publish = "public"

	# How to build site
	command = "yarn run build"

	# Where to run functions from
	functions = "dist/functions/"

[[headers]]
	# Cache Control #
	for = "/css/*"
	[headers.values]
		Cache-Control = "public, max-age=86400"

	for = "/images/*"
	[headers.values]
		Cache-Control = "public, max-age=86400"

	[headers.values]
	for = "/dist/*"
		Cache-Control = "public, max-age=86400"