[build]
	# Where to serve site from
	publish = "public"

	# How to build site
	command = "yarn run build"

	# Where to run functions from
	functions = "dist/functions/"

[[headers]]
	# Cache Control #
	for = "/css/*"
		cache-control: public, max-age=86400
	for = "/images/*"
		cache-control: public, max-age=86400
	for = "/dist/*"
		cache-control: public, max-age=86400