[build]
	# Where to serve site from
	publish = "public"

	# How to build site
	command = "yarn run build"

	# Where to run functions from
	functions = "dist"
	
[[redirect]]
  from = "/api/utility"
  to = "/.netlify/functions/utility-data"
  status = 200
  

# Cache Control #
[[headers]]
	for = "/css/*"
	[headers.values]
		Cache-Control = "public, max-age=86400"

[[headers]]
	for = "/images/*"
	[headers.values]
		Cache-Control = "public, max-age=86400"

[[headers]]
	for = "/dist/*"
	[headers.values]
		Cache-Control = "public, max-age=86400"
